/*
WHERE CLAUSE  ->
The WHERE clause is used to filter records in a table based on a specified condition. Only rows that satisfy the condition will be returned in the query result.
*/


1) WAQTD DETAILS OF SMITH

SELECT *
FROM EMP
WHERE ENAME='SMITH';

2) WAQTD DESIGNATION OF ALLEN.

 SELECT JOB
 FROM EMP
 WHERE ENAME='ALLEN';

3) WAQTD SALARY OF SCOTT.

SELECT SAL
FROM EMP
WHERE ENAME='SCOTT';


4) WAQTD NAMES OF AN EMP EARNING COMMESSION MORE THAN 500.


SELECT ENAME
FROM EMP
WHERE COMM>500;

5) WAQTD DETAILS OF AN EMP HIREDATE AFTER 1981.


 SELECT *
 FROM EMP
 WHERE HIREDATE >'28-SEP-1981';

/*
WHERE CLAUSE  ->
We can pass multiple conditions in WHERE CLAUSE seperated by logical operators.
*/

6) WAQTD NAMES OF AN EMP WORKING AS A CLEARL AND EARNING LESS THAN 1000.
	
 SELECT ENAME
 FROM EMP
 WHERE JOB='CLERK'
 AND SAL<1000;	

7) WAQTD NAMES OF AN EMP WORKING AS SALESMANIN DEPTNO 20.

 SELECT ENAME
 FROM EMP
 WHERE JOB='SALESMAN'
 AND DEPTNO=20;

8)WQATD SALARY OF PRESIDENT.

 SELECT SAL
 FROM EMP
 WHERE JOB='PRESIDENT';

9) WAQTD DETAILS OF AN EMP WORKING AS PRESIDENT OR HIRED BEFORE 1981.


 SELECT *
 FROM EMP
 WHERE JOB='PRESIDENT' OR
 HIREDATE < '01-JAN-1981';

10) WAQTD DETAILS OF AN EMP WORKING IN DEPTNO10 OR 20.

 SELECT *
 FROM EMP
 WHERE DEPTNO=10 OR 
 DEPTNO=20;

11) WAQTD DETAILS OF AN EMP WORKING IN DEPTNO 20 OR 30.

 SELECT *
 FROM EMP
 WHERE DEPTNO=20 OR
 DEPTNO=30;
